version: '3'

services:
  base: &base
    image: chatwoot/chatwoot:latest
    env_file: .env ## Change this file for customized env variables
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      # Commented out local storage for Stateless architecture using SeaweedFS (S3)
      # - ./data/storage:/app/storage
      - ./data/GeoLite2-City.mmdb:/app/vendor/db/GeoLiteCity.mmdb
      - ./config/routes.rb:/app/config/routes.rb
      - ./app/models/concerns/auto_assignment_handler.rb:/app/app/models/concerns/auto_assignment_handler.rb
      - ./app/views/widget_tests/index.html.erb:/app/app/views/widget_tests/index.html.erb

    sysctls:
      net.ipv6.conf.all.disable_ipv6: 1
      net.ipv6.conf.default.disable_ipv6: 1

  rails:
    <<: *base
    depends_on:
      - postgres
      - redis
      - seaweedfs
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    entrypoint: docker/entrypoints/rails.sh
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']
    restart: always

  sidekiq:
    <<: *base
    depends_on:
      - postgres
      - redis
      - seaweedfs
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']
    restart: always

  postgres:
    image: pgvector/pgvector:pg16
    restart: always
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./docker/postgres/init-maxkb.sql:/docker-entrypoint-initdb.d/init-maxkb.sql
    env_file: .env
    environment:
      - POSTGRES_DB=chatwoot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  redis:
    image: redis:alpine
    restart: always
    command: ["sh", "-c", "redis-server --requirepass \"$REDIS_PASSWORD\""]
    env_file: .env
    volumes:
      - ./data/redis:/data
    ports:
      - '127.0.0.1:6379:6379'

  seaweedfs:
    image: chrislusf/seaweedfs:latest
    container_name: seaweedfs
    restart: always
    command: "server -s3 -dir=/data"
    ports:
      - '127.0.0.1:8333:8333'
      - '127.0.0.1:9333:9333'
    volumes:
      - ./data/seaweedfs:/data

  maxkb:
    image: jasonsoft/maxkb:latest
    container_name: maxkb
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - '8080:8080'
    volumes:
      - ./data/maxkb:/opt/maxkb
    depends_on:
      - postgres
      - redis
    env_file: .env
    environment:
      - TZ=Asia/Shanghai
      - MAXKB_DB_HOST=postgres
      - MAXKB_DB_PORT=5432
      - MAXKB_DB_NAME=maxkb
      - MAXKB_DB_USER=postgres
      - MAXKB_DB_PASSWORD=${POSTGRES_PASSWORD}
      - MAXKB_REDIS_HOST=redis
      - MAXKB_REDIS_PORT=6379
      - MAXKB_REDIS_DB=1
      - MAXKB_REDIS_PASSWORD=${REDIS_PASSWORD}
      - MAXKB_SANDBOX=0
